version: 0.0

os: linux

files:
  - source:  / # 현재 프로젝트의 루트 경로
    destination: /home/ec2-user/  # EC2 내부 배포 할 위치
    overwrite: yes # 덮어쓰기

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
